### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by DanielVoogsgerd** [epi-project/brane#98]
Okay, I am getting quite a few errors when running the tests.

@lut99 Wasn't [this](https://github.com/epi-project/brane/commit/104dbe302ba8360810f8a22ae0a413b61ca5fd2b) commit supposed to fix this?

I can take a look at it next week (hopefully).

I will mark the tests in CI as `continue_on_failure` until we have fixed this.

```

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 14 tests
test edgebuffer::tests::test_edgebuffer ... ok
test traversals::compile::tests::test_compile ... FAILED
test traversals::flatten::tests::test_flatten ... FAILED
test traversals::location::tests::test_location ... FAILED
test traversals::attributes::tests::test_attributes ... FAILED
test traversals::data::tests::test_data ... FAILED
test traversals::print::dsl::tests::test_print ... FAILED
test traversals::null::tests::test_null ... FAILED
test traversals::typing::tests::test_typing ... FAILED
test traversals::resolve::tests::test_resolve ... FAILED
test traversals::metadata::tests::test_metadata ... FAILED
test traversals::prune::tests::test_prune ... FAILED
test traversals::workflow_optimize::tests::test_workflow_optimize ... FAILED
test traversals::workflow_resolve::tests::test_workflow_resolve ... FAILED

failures:

---- traversals::compile::tests::test_compile stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::compile::tests::test_compile' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3

---- traversals::flatten::tests::test_flatten stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::flatten::tests::test_flatten' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3

---- traversals::location::tests::test_location stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::location::tests::test_location' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3

---- traversals::attributes::tests::test_attributes stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::attributes::tests::test_attributes' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- traversals::data::tests::test_data stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::data::tests::test_data' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3

---- traversals::print::dsl::tests::test_print stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::print::dsl::tests::test_print' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3

---- traversals::null::tests::test_null stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::null::tests::test_null' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3

---- traversals::typing::tests::test_typing stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::typing::tests::test_typing' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3

---- traversals::resolve::tests::test_resolve stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::resolve::tests::test_resolve' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3

---- traversals::metadata::tests::test_metadata stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::metadata::tests::test_metadata' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3

---- traversals::prune::tests::test_prune stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::prune::tests::test_prune' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3

---- traversals::workflow_optimize::tests::test_workflow_optimize stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::workflow_optimize::tests::test_workflow_optimize' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3

---- traversals::workflow_resolve::tests::test_workflow_resolve stdout ----
--------------------------------------------------------------------------------
File '../tests/branescript/recursion.bs' gave us:
thread 'traversals::workflow_resolve::tests::test_workflow_resolve' panicked at $HOME/work/epi-project/brane/main/brane-shr/src/utilities.rs:185:33:
Failed to read '../tests/data/test/test.yml' as AssetInfo: Failed to parse asset info file '../tests/data/test/test.yml': access: invalid type: map, expected a YAML tag starting with '!' at line 14 column 3


failures:
    traversals::attributes::tests::test_attributes
    traversals::compile::tests::test_compile
    traversals::data::tests::test_data
    traversals::flatten::tests::test_flatten
    traversals::location::tests::test_location
    traversals::metadata::tests::test_metadata
    traversals::null::tests::test_null
    traversals::print::dsl::tests::test_print
    traversals::prune::tests::test_prune
    traversals::resolve::tests::test_resolve
    traversals::typing::tests::test_typing
    traversals::workflow_optimize::tests::test_workflow_optimize
    traversals::workflow_resolve::tests::test_workflow_resolve

test result: FAILED. 1 passed; 13 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s


```

**Comment by DanielVoogsgerd** [comment]
Nevermind, this was fixed on develop. I thought it was already merged into main, my bad, apologies.

**Comment by Lut99** [comment]
No worries, I think I made that mistake too xD

Although I also think the fix I originally implemented was accidentally partial. Either way, I remember bumping into this a second time and then fixing it indeed.
